export const LOAD_RECIPES = "LOAD_RECIPES";
export const LOAD_RECIPES_IN_PROGRESS = "LOAD_RECIPES_IN_PROGRESS";
export const LOAD_RECIPES_FAILED = "LOAD_RECIPES_FAILED";

export const LOAD_MY_RECIPES = "LOAD_MY_RECIPES";
export const LOAD_MY_RECIPES_IN_PROGRESS = "LOAD_MY_RECIPES_IN_PROGRESS";
export const LOAD_MY_RECIPES_FAILED = "LOAD_MY_RECIPES_FAILED";


export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_IN_PROGRESS = "LOGIN_IN_PROGRESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGNOUT = "SIGNOUT";

export const ADD_USERS = "ADD_USERS";