export const LOAD_RECIPES = "LOAD_RECIPES";
export const LOAD_RECIPES_IN_PROGRESS = "LOAD_RECIPES_IN_PROGRESS";
export const LOAD_RECIPES_FAILED = "LOAD_RECIPES_FAILED";

export const LOAD_MY_RECIPES = "LOAD_MY_RECIPES";
export const LOAD_MY_RECIPES_IN_PROGRESS = "LOAD_MY_RECIPES_IN_PROGRESS";
export const LOAD_MY_RECIPES_FAILED = "LOAD_MY_RECIPES_FAILED";
export const LOAD_MY_RECIPES_RESET = "LOAD_MY_RECIPES_RESET";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_IN_PROGRESS = "LOGIN_IN_PROGRESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_IN_PROGRESS = "SIGNUP_IN_PROGRESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const SIGNOUT = "SIGNOUT";

export const ADD_USERS = "ADD_USERS";

export const GET_RECIPE_FAILED = "GET_RECIPE_FAILED";
export const GET_RECIPE_IN_PROGRESS = "GET_RECIPE_IN_PROGRESS";
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const GET_RECIPE_RESET = "GET_RECIPE_RESET";

export const UPDATE_RECIPE_IN_PROGRESS = "UPDATE_RECIPE_IN_PROGRESS";
export const UPDATE_RECIPE_FAILED = "UPDATE_RECIPE_FAILED";
export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS";

// export const LOAD_GROCERYLIST = "LOAD_GROCERYLIST";
export const LOAD_GROCERYLIST_IN_PROGRESS = "LOAD_GROCERYLIST_IN_PROGRESS";
export const LOAD_GROCERYLIST_FAILED = "LOAD_GROCERYLIST_FAILED";
export const LOAD_GROCERYLIST_SUCCESS = "LOAD_GROCERYLIST_SUCCESS";
export const LOAD_GROCERYLIST_RESET = "LOAD_GROCERYLIST_RESET";

export const LOAD_LIST_SUCCESS = "LOAD_LIST_SUCCESS";
export const LOAD_LIST_IN_PROGRESS = "LOAD_LIST_IN_PROGRESS";
export const LOAD_LIST_FAILED = "LOAD_LIST_FAILED";
export const LOAD_LIST_RESET = "LOAD_LIST_RESET";